### ISSUE TITLE
Issue with change/delete

### ISSUE THREAD

**Issue by bitfade** [PythonNut/evil-easymotion#16] opened 2015-06-11 17:03 UTC
First of all, thanks for this nice plugin.

Found an issue when using easymotion with change/delete

with the following example, cursot at |

    (|evilem-default-keybindings "SPC")

df-

    (default-keybindings "SPC")

using easymotion dSPCf-a

    (-default-keybindings "SPC")

the last char isn't included

**Comment by PythonNut** [comment] 2015-06-11 17:22
Ah. Thank you. I've reproduced it, and I think I know what the problem is.

**Comment by PythonNut** [comment] 2015-06-11 17:28
Should be fixed now.

**Comment by bitfade** [comment] 2015-06-11 20:15
Holy crap if that was fast.

It works as expected now, thx a lot.

**Comment by bitfade** [comment] 2015-06-12 13:46
Hello,

the fix has a side effect, consider the case

    |abc
    abc
    abc

dSPCjs

    bc

so now it includes an extra char. The previous version worked as expected

**Comment by PythonNut** [comment] 2015-06-12 14:40
Dang, so the fix isn't quite so simple. Let me see...

**Comment by PythonNut** [comment] 2015-06-12 14:43
For some reason, I can't seem to reproduce. I added

```
abc
abc
abc
```

To `*scratch*` and did <kbd>d</kbd> <kbd>SPC</kbd> <kbd>j</kbd> <kbd>k</kbd> (my `avy-keys` is different`), and I got the expected result.

**Comment by bitfade** [comment] 2015-06-12 15:27
I created a test here

https://gist.github.com/bitfade/367698255116516077a4

**Comment by PythonNut** [comment] 2015-06-12 15:30
Ah. Thanks. This is a bit trickier.

**Comment by PythonNut** [comment] 2015-06-12 16:24
Try it now. The problem was that it was treating line oriented motions as character motions, should be fixed now that the motion type is overridden.

**Closed** 2015-06-12 16:23 UTC

**Comment by bitfade** [comment] 2015-06-12 16:59
yep, all good now.

i'm using some custom functions and they're working as expected now after i set evil-this-type to line

thx a lot mate.

**Comment by PythonNut** [comment] 2015-06-12 16:59
Cool. You're welcome.
